//! SDP (Session Description Protocol) generation for AES67 blocks.
//!
//! Implements RFC 7273 clock signaling for AES67 streams:
//! - ts-refclk: indicates the reference clock (PTP, NTP, or local)
//! - mediaclk: indicates media clock relationship to reference clock

use gstreamer as gst;
use strom_types::flow::{FlowProperties, GStreamerClockType};
use strom_types::{BlockInstance, PropertyValue};

/// Convert PTP clock ID from colon-separated format (XX:XX:XX:XX:XX:XX:XX:XX)
/// to hyphen-separated format (xx-xx-xx-xx-xx-xx-xx-xx) as required by RFC 7273.
/// Uses lowercase hex for better interoperability with RAVENNA/AES67 devices.
pub fn convert_clock_id_to_sdp_format(clock_id: &str) -> String {
    clock_id.replace(':', "-").to_lowercase()
}

/// Sanitize a session name for use in SDP s= field per RFC 4566.
///
/// RFC 4566 requirements:
/// - MUST NOT be empty (returns " " if empty)
/// - MUST NOT contain NUL (0x00), CR (0x0D), or LF (0x0A)
/// - Should be UTF-8 encoded (ISO-10646)
pub fn sanitize_session_name(name: &str) -> String {
    // Remove forbidden characters: NUL, CR, LF
    let sanitized: String = name
        .chars()
        .filter(|c| *c != '\0' && *c != '\r' && *c != '\n')
        .collect();

    // MUST NOT be empty - use single space if empty
    if sanitized.trim().is_empty() {
        " ".to_string()
    } else {
        sanitized
    }
}

/// Extract audio format details from GStreamer caps.
/// Returns (sample_rate, channels) or None if the caps don't contain audio info.
pub fn parse_audio_caps(caps: &gst::Caps) -> Option<(i32, i32)> {
    // Get the first structure from the caps
    let structure = caps.structure(0)?;

    // Check if it's audio caps
    let name = structure.name();
    if !name.starts_with("audio/") {
        return None;
    }

    // Extract sample rate (field name is "rate")
    let sample_rate = structure.get::<i32>("rate").ok()?;

    // Extract channels
    let channels = structure.get::<i32>("channels").ok()?;

    Some((sample_rate, channels))
}

/// Generate the ts-refclk attribute based on flow clock configuration.
///
/// Per RFC 7273:
/// - PTP: `a=ts-refclk:ptp=IEEE1588-2008:<clock-identity>:<domain>`
/// - NTP: `a=ts-refclk:ntp=<server>` or `a=ts-refclk:ntp=/traceable/`
/// - Local/other: `a=ts-refclk:local`
///
/// The `ptp_clock_identity` parameter is optional - if not provided for PTP,
/// a placeholder identity will be used.
pub fn generate_ts_refclk(
    flow_properties: Option<&FlowProperties>,
    ptp_clock_identity: Option<&str>,
) -> String {
    let props = match flow_properties {
        Some(p) => p,
        None => {
            // Default to local sender clock when no properties specified
            return "a=ts-refclk:local".to_string();
        }
    };

    match props.clock_type {
        GStreamerClockType::Ptp => {
            let domain = props.ptp_domain.unwrap_or(0);
            // Use provided clock identity or placeholder
            // Clock identity format: XX-XX-XX-FF-FE-XX-XX-XX (8 bytes, hyphen-separated)
            let identity = ptp_clock_identity.unwrap_or("00-00-00-FF-FE-00-00-00");
            format!("a=ts-refclk:ptp=IEEE1588-2008:{}:{}", identity, domain)
        }
        GStreamerClockType::Ntp => {
            // Use specific NTP server if configured, otherwise use traceable
            match &props.ntp_server {
                Some(server) => format!("a=ts-refclk:ntp={}", server),
                None => "a=ts-refclk:ntp=/traceable/".to_string(),
            }
        }
        GStreamerClockType::Monotonic | GStreamerClockType::Realtime | GStreamerClockType::Tai => {
            // Kernel-provided system clocks — reference is the local sender.
            "a=ts-refclk:local".to_string()
        }
    }
}

/// Generate the mediaclk attribute based on flow clock configuration.
///
/// Per RFC 7273:
/// - `direct=0`: Media clock is directly related to the reference clock with
///   zero offset. Used when the flow has `direct_media_timing=true` — the
///   pipeline is then configured with `base_time=0` and RTP timestamps reflect
///   the reference clock directly (required for AES67).
/// - `sender`: Media clock is asynchronously generated by the sender. Used
///   otherwise.
pub fn generate_mediaclk(flow_properties: Option<&FlowProperties>) -> String {
    let props = match flow_properties {
        Some(p) => p,
        None => {
            // Default to sender (asynchronous) when no properties specified
            return "a=mediaclk:sender".to_string();
        }
    };

    if props.effective_direct_media_timing() {
        "a=mediaclk:direct=0".to_string()
    } else {
        "a=mediaclk:sender".to_string()
    }
}

/// Check if an IP address is multicast (224.0.0.0 to 239.255.255.255).
fn is_multicast_address(addr: &str) -> bool {
    // Try to parse as IPv4 address
    let parts: Vec<&str> = addr.split('.').collect();
    if parts.len() != 4 {
        return false;
    }

    // Parse first octet
    if let Ok(first_octet) = parts[0].parse::<u8>() {
        // Multicast range is 224-239 (class D)
        (224..=239).contains(&first_octet)
    } else {
        false
    }
}

/// Generate SDP for an AES67 output block instance.
///
/// The SDP describes the RTP stream parameters that receivers need to connect.
/// Uses configured block properties for accurate stream description.
///
/// # Clock Signaling (RFC 7273)
///
/// The `flow_properties` parameter controls clock signaling in the SDP:
///
/// Reference clock (ts-refclk):
/// - PTP clock: `a=ts-refclk:ptp=IEEE1588-2008:<identity>:<domain>`
/// - NTP clock: `a=ts-refclk:ntp=<server>` or `a=ts-refclk:ntp=/traceable/`
/// - Local/system clock: `a=ts-refclk:local`
///
/// Media clock (mediaclk) — driven by `FlowProperties::effective_direct_media_timing()`:
/// - `direct_media_timing` true (explicit, or Auto with `clock_type=Ptp`):
///   `a=mediaclk:direct=0` — RTP timestamps map directly to the reference clock.
/// - `direct_media_timing` false (explicit, or Auto with any other clock type):
///   `a=mediaclk:sender` — asynchronously generated by the sender.
///
/// The `ptp_clock_identity` parameter can provide the actual PTP clock identity
/// for accurate signaling when using PTP.
///
/// The `origin_ip` parameter specifies the source IP address for the SDP origin line
/// and source-filter attribute. If None, defaults to "0.0.0.0".
///
/// # RAVENNA Extensions
///
/// When `ravenna_extensions` is true, the following additional attributes are included:
/// - `a=clock-domain:PTPv2 <domain>` - Indicates the PTP domain
/// - `a=framecount:<samples>` - Number of samples per RTP packet
/// - `a=sync-time:0` - Synchronization offset (always 0 for direct clock mapping)
#[allow(clippy::too_many_arguments)]
pub fn generate_aes67_output_sdp(
    block: &BlockInstance,
    session_name: &str,
    sample_rate: Option<i32>,
    channels: Option<i32>,
    flow_properties: Option<&FlowProperties>,
    ptp_clock_identity: Option<&str>,
    origin_ip: Option<&str>,
    ravenna_extensions: bool,
) -> String {
    // Extract properties or use defaults
    let host = block
        .properties
        .get("host")
        .and_then(|v| {
            if let PropertyValue::String(s) = v {
                Some(s.as_str())
            } else {
                None
            }
        })
        .unwrap_or("239.69.1.1");

    let port = block
        .properties
        .get("port")
        .and_then(|v| {
            if let PropertyValue::Int(i) = v {
                Some(*i)
            } else {
                None
            }
        })
        .unwrap_or(5004);

    // Get bit depth to determine L16 vs L24
    let bit_depth = block
        .properties
        .get("bit_depth")
        .and_then(|v| match v {
            PropertyValue::Int(i) => Some(*i as i32),
            PropertyValue::String(s) => s.parse::<i32>().ok(),
            _ => None,
        })
        .unwrap_or(24);

    // Get packet time (ptime) in milliseconds
    let ptime = block
        .properties
        .get("ptime")
        .and_then(|v| match v {
            PropertyValue::Float(f) => Some(*f),
            PropertyValue::String(s) => s.parse::<f64>().ok(),
            _ => None,
        })
        .unwrap_or(1.0);

    // Get multicast TTL (default 32)
    let ttl = block
        .properties
        .get("ttl")
        .and_then(|v| {
            if let PropertyValue::Int(i) = v {
                Some(*i as i32)
            } else {
                None
            }
        })
        .unwrap_or(32);

    // Use provided origin IP or default to 0.0.0.0
    let origin_ip = origin_ip.unwrap_or("0.0.0.0");

    // Session ID and version (using timestamp)
    let session_id = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();

    // Use provided values or fall back to AES67 defaults: 48kHz, 2 channels
    let sample_rate = sample_rate.unwrap_or(48000);
    let channels = channels.unwrap_or(2);

    // RTP payload type - must match the "pt" property set on the payloader
    let payload_type = block
        .properties
        .get("payload_type")
        .and_then(|v| match v {
            PropertyValue::Int(i) => Some(*i),
            PropertyValue::String(s) => s.parse::<i64>().ok(),
            _ => None,
        })
        .filter(|pt| (0..=127).contains(pt))
        .unwrap_or(strom_types::block::DEFAULT_AES67_OUTPUT_PAYLOAD_TYPE);

    // Determine encoding name based on bit depth
    let encoding = match bit_depth {
        16 => "L16",
        24 => "L24",
        _ => "L24", // Default to 24-bit
    };

    // Check if the host is a multicast address and format connection line accordingly
    // Multicast IPv4 addresses are in range 224.0.0.0 to 239.255.255.255
    // For multicast, format is: c=IN IP4 <address>/<ttl>
    let is_multicast = is_multicast_address(host);
    let connection_line = if is_multicast {
        format!("c=IN IP4 {}/{}", host, ttl)
    } else {
        format!("c=IN IP4 {}", host) // No TTL for unicast
    };

    // Generate source-filter for multicast addresses (RFC 4570)
    // This helps receivers know the expected source for the multicast stream
    let source_filter = if is_multicast {
        format!("a=source-filter: incl IN IP4 {} {}\r\n", host, origin_ip)
    } else {
        String::new()
    };

    // Generate clock signaling attributes per RFC 7273
    let ts_refclk = generate_ts_refclk(flow_properties, ptp_clock_identity);
    let mediaclk = generate_mediaclk(flow_properties);

    // Generate RAVENNA extensions if enabled
    // Session-level: clock-domain (before m= line)
    // Media-level: framecount, sync-time (after m= line)
    //
    // Note: ts-refclk and mediaclk are ALWAYS included at media level per RFC 7273,
    // as many AES67 devices (including Lawo/RAVENNA) expect them there.
    let session_ravenna = if ravenna_extensions {
        let ptp_domain = flow_properties.and_then(|p| p.ptp_domain).unwrap_or(0);
        format!("a=clock-domain:PTPv2 {}\r\n", ptp_domain)
    } else {
        String::new()
    };

    // Always include ts-refclk and mediaclk at media level for AES67 interoperability
    let media_clock_attrs = format!("{}\r\n{}\r\n", ts_refclk, mediaclk);

    // Additional RAVENNA-specific media attributes
    let media_ravenna = if ravenna_extensions {
        // Calculate framecount from ptime and sample rate
        // framecount = ptime_ms * sample_rate / 1000
        let framecount = (ptime * sample_rate as f64 / 1000.0).round() as i32;
        format!("a=sync-time:0\r\na=framecount:{}\r\n", framecount)
    } else {
        String::new()
    };

    // Generate SDP
    // Structure follows RFC 4566 with AES67/RAVENNA extensions:
    // v= (version)
    // o= (origin)
    // s= (session name)
    // c= (connection)
    // t= (timing)
    // a= (session-level attributes: ts-refclk, mediaclk, clock-domain)
    // m= (media description)
    // a= (media-level attributes: source-filter, rtpmap, ptime, etc.)
    format!(
        "v=0\r
o=- {} {} IN IP4 {}\r
s={}\r
{}\r
t=0 0\r
{}\r
{}\r
{}m=audio {} RTP/AVP {}\r
{}a=rtpmap:{} {}/{}/{}\r
a=ptime:{}\r
a=recvonly\r
{}{}",
        session_id,
        session_id,
        origin_ip,
        session_name,
        connection_line,
        ts_refclk,
        mediaclk,
        session_ravenna,
        port,
        payload_type,
        source_filter,
        payload_type,
        encoding,
        sample_rate,
        channels,
        ptime,
        media_clock_attrs,
        media_ravenna
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    #[test]
    fn test_parse_audio_caps_44100_mono() {
        gst::init().unwrap();

        // Create caps for 44.1kHz mono audio (audiotestsrc default)
        let caps = gst::Caps::builder("audio/x-raw")
            .field("rate", 44100i32)
            .field("channels", 1i32)
            .build();

        let result = parse_audio_caps(&caps);
        assert_eq!(result, Some((44100, 1)));
    }

    #[test]
    fn test_parse_audio_caps_48000_stereo() {
        gst::init().unwrap();

        // Create caps for 48kHz stereo (AES67 standard)
        let caps = gst::Caps::builder("audio/x-raw")
            .field("rate", 48000i32)
            .field("channels", 2i32)
            .build();

        let result = parse_audio_caps(&caps);
        assert_eq!(result, Some((48000, 2)));
    }

    #[test]
    fn test_parse_audio_caps_non_audio() {
        gst::init().unwrap();

        // Create video caps - should return None
        let caps = gst::Caps::builder("video/x-raw")
            .field("width", 1920i32)
            .field("height", 1080i32)
            .build();

        let result = parse_audio_caps(&caps);
        assert_eq!(result, None);
    }

    #[test]
    fn test_generate_sdp_default_values() {
        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties: HashMap::new(),
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let sdp =
            generate_aes67_output_sdp(&block, "Test Stream", None, None, None, None, None, false);

        assert!(sdp.contains("s=Test Stream"));
        assert!(sdp.contains("c=IN IP4 239.69.1.1/32")); // Multicast with default TTL=32
        assert!(sdp.contains("m=audio 5004 RTP/AVP 96"));
        assert!(sdp.contains("a=rtpmap:96 L24/48000/2"));
        // Default clock signaling (no flow properties) should use local/sender
        assert!(sdp.contains("a=ts-refclk:local"));
        assert!(sdp.contains("a=mediaclk:sender"));
        // Multicast should have source-filter with default origin IP
        assert!(sdp.contains("a=source-filter: incl IN IP4 239.69.1.1 0.0.0.0"));
    }

    #[test]
    fn test_generate_sdp_custom_payload_type() {
        let mut properties = HashMap::new();
        properties.insert("payload_type".to_string(), PropertyValue::Int(98));

        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties,
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let sdp =
            generate_aes67_output_sdp(&block, "Test Stream", None, None, None, None, None, false);

        assert!(sdp.contains("m=audio 5004 RTP/AVP 98"));
        assert!(sdp.contains("a=rtpmap:98 L24/48000/2"));
    }

    #[test]
    fn test_generate_sdp_out_of_range_payload_type_falls_back() {
        let mut properties = HashMap::new();
        properties.insert("payload_type".to_string(), PropertyValue::Int(200));

        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties,
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let sdp =
            generate_aes67_output_sdp(&block, "Test Stream", None, None, None, None, None, false);

        assert!(sdp.contains("m=audio 5004 RTP/AVP 96"));
        assert!(sdp.contains("a=rtpmap:96 L24/48000/2"));
    }

    #[test]
    fn test_generate_sdp_custom_values() {
        let mut properties = HashMap::new();
        properties.insert(
            "host".to_string(),
            PropertyValue::String("239.1.2.3".to_string()),
        );
        properties.insert("port".to_string(), PropertyValue::Int(6000));

        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties,
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let sdp = generate_aes67_output_sdp(
            &block,
            "Custom Stream",
            None,
            None,
            None,
            None,
            Some("10.0.0.5"),
            false,
        );

        assert!(sdp.contains("s=Custom Stream"));
        assert!(sdp.contains("c=IN IP4 239.1.2.3/32")); // Multicast with default TTL=32
        assert!(sdp.contains("m=audio 6000 RTP/AVP 96"));
        assert!(sdp.contains("o=- ")); // Origin line should contain our IP
        assert!(sdp.contains(" IN IP4 10.0.0.5"));
        assert!(sdp.contains("a=source-filter: incl IN IP4 239.1.2.3 10.0.0.5"));
    }

    #[test]
    fn test_generate_sdp_with_44100_mono() {
        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties: HashMap::new(),
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        // Test with audiotestsrc defaults: 44.1kHz mono
        let sdp = generate_aes67_output_sdp(
            &block,
            "Test Stream",
            Some(44100),
            Some(1),
            None,
            None,
            None,
            false,
        );

        assert!(sdp.contains("s=Test Stream"));
        assert!(sdp.contains("a=rtpmap:96 L24/44100/1"));
    }

    #[test]
    fn test_generate_sdp_with_string_bit_depth_16() {
        let mut properties = HashMap::new();
        properties.insert(
            "bit_depth".to_string(),
            PropertyValue::String("16".to_string()),
        );

        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties,
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let sdp =
            generate_aes67_output_sdp(&block, "Test Stream", None, None, None, None, None, false);

        // Should use L16 encoding, not L24
        assert!(sdp.contains("a=rtpmap:96 L16/48000/2"));
        assert!(!sdp.contains("a=rtpmap:96 L24")); // Check rtpmap specifically
    }

    #[test]
    fn test_generate_sdp_with_string_bit_depth_24() {
        let mut properties = HashMap::new();
        properties.insert(
            "bit_depth".to_string(),
            PropertyValue::String("24".to_string()),
        );

        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties,
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let sdp =
            generate_aes67_output_sdp(&block, "Test Stream", None, None, None, None, None, false);

        // Should use L24 encoding
        assert!(sdp.contains("a=rtpmap:96 L24/48000/2"));
    }

    #[test]
    fn test_generate_sdp_with_string_ptime() {
        let mut properties = HashMap::new();
        properties.insert(
            "ptime".to_string(),
            PropertyValue::String("4.0".to_string()),
        );

        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties,
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let sdp =
            generate_aes67_output_sdp(&block, "Test Stream", None, None, None, None, None, false);

        // Should have ptime=4.0, not 1.0
        assert!(sdp.contains("a=ptime:4"));
        assert!(!sdp.contains("a=ptime:1\r")); // Be specific to avoid matching session ID
    }

    #[test]
    fn test_generate_sdp_with_all_string_properties() {
        let mut properties = HashMap::new();
        properties.insert(
            "bit_depth".to_string(),
            PropertyValue::String("16".to_string()),
        );
        properties.insert(
            "sample_rate".to_string(),
            PropertyValue::String("96000".to_string()),
        );
        properties.insert(
            "ptime".to_string(),
            PropertyValue::String("0.125".to_string()),
        );
        properties.insert("channels".to_string(), PropertyValue::Int(8));
        properties.insert(
            "host".to_string(),
            PropertyValue::String("239.1.2.3".to_string()),
        );
        properties.insert("port".to_string(), PropertyValue::Int(5008));

        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties,
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let sdp = generate_aes67_output_sdp(
            &block,
            "Multi-channel Stream",
            Some(96000),
            Some(8),
            None,
            None,
            None,
            false,
        );

        // Verify all properties are correctly reflected in SDP
        assert!(sdp.contains("s=Multi-channel Stream"));
        assert!(sdp.contains("c=IN IP4 239.1.2.3/32")); // Multicast with default TTL=32
        assert!(sdp.contains("m=audio 5008 RTP/AVP 96"));
        assert!(sdp.contains("a=rtpmap:96 L16/96000/8")); // L16 for 16-bit
        assert!(sdp.contains("a=ptime:0.125")); // 0.125 ms ptime
    }

    #[test]
    fn test_multicast_address_detection() {
        // Test multicast addresses (224.0.0.0 to 239.255.255.255)
        assert!(is_multicast_address("224.0.0.0"));
        assert!(is_multicast_address("239.255.255.255"));
        assert!(is_multicast_address("239.69.11.44"));
        assert!(is_multicast_address("225.1.2.3"));

        // Test non-multicast addresses
        assert!(!is_multicast_address("127.0.0.1"));
        assert!(!is_multicast_address("192.168.1.1"));
        assert!(!is_multicast_address("10.0.0.1"));
        assert!(!is_multicast_address("223.255.255.255")); // Just below multicast range
        assert!(!is_multicast_address("240.0.0.0")); // Just above multicast range

        // Test invalid addresses
        assert!(!is_multicast_address("invalid"));
        assert!(!is_multicast_address("999.999.999.999"));
        assert!(!is_multicast_address(""));
    }

    #[test]
    fn test_generate_sdp_unicast_no_ttl() {
        let mut properties = HashMap::new();
        properties.insert(
            "host".to_string(),
            PropertyValue::String("192.168.1.100".to_string()),
        );

        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties,
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let sdp = generate_aes67_output_sdp(
            &block,
            "Unicast Stream",
            None,
            None,
            None,
            None,
            None,
            false,
        );

        // Unicast addresses should NOT have /TTL suffix
        assert!(sdp.contains("c=IN IP4 192.168.1.100\r"));
        assert!(!sdp.contains("/32"));
        // Unicast should NOT have source-filter
        assert!(!sdp.contains("a=source-filter:"));
    }

    #[test]
    fn test_generate_sdp_multicast_has_ttl() {
        let mut properties = HashMap::new();
        properties.insert(
            "host".to_string(),
            PropertyValue::String("239.69.11.44".to_string()),
        );

        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties,
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let sdp = generate_aes67_output_sdp(
            &block,
            "Multicast Stream",
            None,
            None,
            None,
            None,
            Some("192.168.1.50"),
            false,
        );

        // Multicast addresses MUST have /TTL suffix (default TTL=32)
        assert!(sdp.contains("c=IN IP4 239.69.11.44/32\r"));
        // Multicast should have source-filter
        assert!(sdp.contains("a=source-filter: incl IN IP4 239.69.11.44 192.168.1.50"));
    }

    #[test]
    fn test_generate_sdp_custom_ttl() {
        let mut properties = HashMap::new();
        properties.insert(
            "host".to_string(),
            PropertyValue::String("239.69.11.44".to_string()),
        );
        properties.insert("ttl".to_string(), PropertyValue::Int(64));

        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties,
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let sdp = generate_aes67_output_sdp(
            &block,
            "Custom TTL Stream",
            None,
            None,
            None,
            None,
            Some("192.168.1.50"),
            false,
        );

        // Custom TTL=64 should be reflected in connection line
        assert!(sdp.contains("c=IN IP4 239.69.11.44/64\r"));
    }

    // RFC 7273 clock signaling tests

    #[test]
    fn test_ts_refclk_ptp() {
        let props = FlowProperties {
            clock_type: GStreamerClockType::Ptp,
            ptp_domain: Some(42),
            ..Default::default()
        };

        let ts_refclk = generate_ts_refclk(Some(&props), Some("AA-BB-CC-FF-FE-DD-EE-FF"));
        assert_eq!(
            ts_refclk,
            "a=ts-refclk:ptp=IEEE1588-2008:AA-BB-CC-FF-FE-DD-EE-FF:42"
        );
    }

    #[test]
    fn test_ts_refclk_ptp_default_domain() {
        let props = FlowProperties {
            clock_type: GStreamerClockType::Ptp,
            ptp_domain: None,
            ..Default::default()
        };

        let ts_refclk = generate_ts_refclk(Some(&props), None);
        assert_eq!(
            ts_refclk,
            "a=ts-refclk:ptp=IEEE1588-2008:00-00-00-FF-FE-00-00-00:0"
        );
    }

    #[test]
    fn test_ts_refclk_ntp_with_server() {
        let props = FlowProperties {
            clock_type: GStreamerClockType::Ntp,
            ntp_server: Some("ntp.example.com".to_string()),
            ..Default::default()
        };

        let ts_refclk = generate_ts_refclk(Some(&props), None);
        assert_eq!(ts_refclk, "a=ts-refclk:ntp=ntp.example.com");
    }

    #[test]
    fn test_ts_refclk_ntp_traceable() {
        let props = FlowProperties {
            clock_type: GStreamerClockType::Ntp,
            ntp_server: None,
            ..Default::default()
        };

        let ts_refclk = generate_ts_refclk(Some(&props), None);
        assert_eq!(ts_refclk, "a=ts-refclk:ntp=/traceable/");
    }

    #[test]
    fn test_ts_refclk_local() {
        let props = FlowProperties {
            clock_type: GStreamerClockType::Monotonic,
            ..Default::default()
        };

        let ts_refclk = generate_ts_refclk(Some(&props), None);
        assert_eq!(ts_refclk, "a=ts-refclk:local");
    }

    #[test]
    fn test_ts_refclk_no_properties() {
        let ts_refclk = generate_ts_refclk(None, None);
        assert_eq!(ts_refclk, "a=ts-refclk:local");
    }

    #[test]
    fn test_mediaclk_ptp() {
        let props = FlowProperties {
            clock_type: GStreamerClockType::Ptp,
            ..Default::default()
        };
        let mediaclk = generate_mediaclk(Some(&props));
        assert_eq!(mediaclk, "a=mediaclk:direct=0");
    }

    #[test]
    fn test_mediaclk_ntp() {
        // NTP uses default base_time (not direct timing), so mediaclk is sender.
        let props = FlowProperties {
            clock_type: GStreamerClockType::Ntp,
            ntp_server: Some("pool.ntp.org".to_string()),
            ..Default::default()
        };
        let mediaclk = generate_mediaclk(Some(&props));
        assert_eq!(mediaclk, "a=mediaclk:sender");
    }

    #[test]
    fn test_mediaclk_monotonic() {
        let props = FlowProperties {
            clock_type: GStreamerClockType::Monotonic,
            ..Default::default()
        };
        let mediaclk = generate_mediaclk(Some(&props));
        assert_eq!(mediaclk, "a=mediaclk:sender");
    }

    #[test]
    fn test_mediaclk_realtime() {
        // Realtime uses default base_time, so the media clock is free-running.
        let props = FlowProperties {
            clock_type: GStreamerClockType::Realtime,
            ..Default::default()
        };
        let mediaclk = generate_mediaclk(Some(&props));
        assert_eq!(mediaclk, "a=mediaclk:sender");
    }

    #[test]
    fn test_mediaclk_tai_default() {
        // TAI without explicit direct_media_timing defaults to off.
        let props = FlowProperties {
            clock_type: GStreamerClockType::Tai,
            ..Default::default()
        };
        let mediaclk = generate_mediaclk(Some(&props));
        assert_eq!(mediaclk, "a=mediaclk:sender");
    }

    #[test]
    fn test_mediaclk_tai_direct_opt_in() {
        // TAI with direct_media_timing=Some(true) → direct=0
        // (use case: AES67 with system TAI disciplined via ptp4l/phc2sys).
        let props = FlowProperties {
            clock_type: GStreamerClockType::Tai,
            direct_media_timing: Some(true),
            ..Default::default()
        };
        let mediaclk = generate_mediaclk(Some(&props));
        assert_eq!(mediaclk, "a=mediaclk:direct=0");
    }

    #[test]
    fn test_mediaclk_ptp_default_is_direct() {
        // PTP defaults to direct=0 (AES67 / RFC 7273 contract).
        let props = FlowProperties {
            clock_type: GStreamerClockType::Ptp,
            ..Default::default()
        };
        let mediaclk = generate_mediaclk(Some(&props));
        assert_eq!(mediaclk, "a=mediaclk:direct=0");
    }

    #[test]
    fn test_mediaclk_ptp_explicit_off() {
        // PTP with direct_media_timing=Some(false) → sender (explicit override).
        let props = FlowProperties {
            clock_type: GStreamerClockType::Ptp,
            direct_media_timing: Some(false),
            ..Default::default()
        };
        let mediaclk = generate_mediaclk(Some(&props));
        assert_eq!(mediaclk, "a=mediaclk:sender");
    }

    #[test]
    fn test_ts_refclk_tai() {
        let props = FlowProperties {
            clock_type: GStreamerClockType::Tai,
            ..Default::default()
        };
        let ts_refclk = generate_ts_refclk(Some(&props), None);
        assert_eq!(ts_refclk, "a=ts-refclk:local");
    }

    #[test]
    fn test_mediaclk_no_properties() {
        let mediaclk = generate_mediaclk(None);
        assert_eq!(mediaclk, "a=mediaclk:sender");
    }

    #[test]
    fn test_generate_sdp_with_ptp_clock() {
        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties: HashMap::new(),
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let flow_props = FlowProperties {
            clock_type: GStreamerClockType::Ptp,
            ptp_domain: Some(127),
            ..Default::default()
        };

        let sdp = generate_aes67_output_sdp(
            &block,
            "PTP Stream",
            None,
            None,
            Some(&flow_props),
            Some("12-34-56-FF-FE-78-9A-BC"),
            None,
            false,
        );

        assert!(sdp.contains("a=ts-refclk:ptp=IEEE1588-2008:12-34-56-FF-FE-78-9A-BC:127"));
        assert!(sdp.contains("a=mediaclk:direct=0"));
    }

    #[test]
    fn test_generate_sdp_with_ntp_clock() {
        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties: HashMap::new(),
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let flow_props = FlowProperties {
            clock_type: GStreamerClockType::Ntp,
            ntp_server: Some("time.google.com".to_string()),
            ..Default::default()
        };

        let sdp = generate_aes67_output_sdp(
            &block,
            "NTP Stream",
            None,
            None,
            Some(&flow_props),
            None,
            None,
            false,
        );

        assert!(sdp.contains("a=ts-refclk:ntp=time.google.com"));
        // NTP does not use direct media timing in strom (see FlowProperties docs).
        assert!(sdp.contains("a=mediaclk:sender"));
    }

    #[test]
    fn test_generate_sdp_with_monotonic_clock() {
        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties: HashMap::new(),
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let flow_props = FlowProperties {
            clock_type: GStreamerClockType::Monotonic,
            ..Default::default()
        };

        let sdp = generate_aes67_output_sdp(
            &block,
            "Local Stream",
            None,
            None,
            Some(&flow_props),
            None,
            None,
            false,
        );

        // Monotonic clock uses local reference and sender media clock
        assert!(sdp.contains("a=ts-refclk:local"));
        assert!(sdp.contains("a=mediaclk:sender"));
    }

    #[test]
    fn test_generate_sdp_with_ravenna_extensions() {
        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties: HashMap::new(),
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let flow_props = FlowProperties {
            clock_type: GStreamerClockType::Ptp,
            ptp_domain: Some(42),
            ..Default::default()
        };

        // Test with RAVENNA extensions enabled
        let sdp = generate_aes67_output_sdp(
            &block,
            "RAVENNA Stream",
            Some(48000),
            Some(8),
            Some(&flow_props),
            Some("ec-46-70-ff-fe-0a-a1-81"),
            Some("100.67.0.167"),
            true, // Enable RAVENNA extensions
        );

        // Check session-level attributes
        assert!(sdp.contains("a=clock-domain:PTPv2 42"));

        // Check media-level RAVENNA attributes
        // framecount = ptime_ms * sample_rate / 1000 = 1.0 * 48000 / 1000 = 48
        assert!(sdp.contains("a=framecount:48"));
        assert!(sdp.contains("a=sync-time:0"));

        // ts-refclk and mediaclk should appear at media level too when RAVENNA is enabled
        assert!(sdp.contains("a=ts-refclk:ptp=IEEE1588-2008:ec-46-70-ff-fe-0a-a1-81:42"));
        assert!(sdp.contains("a=mediaclk:direct=0"));
    }

    #[test]
    fn test_generate_sdp_without_ravenna_extensions() {
        let block = BlockInstance {
            id: "block_0".to_string(),
            block_definition_id: "builtin.aes67_output".to_string(),
            name: None,
            properties: HashMap::new(),
            position: strom_types::block::Position { x: 0.0, y: 0.0 },
            runtime_data: None,
            computed_external_pads: None,
        };

        let flow_props = FlowProperties {
            clock_type: GStreamerClockType::Ptp,
            ptp_domain: Some(42),
            ..Default::default()
        };

        // Test without RAVENNA extensions
        let sdp = generate_aes67_output_sdp(
            &block,
            "AES67 Stream",
            Some(48000),
            Some(8),
            Some(&flow_props),
            Some("ec-46-70-ff-fe-0a-a1-81"),
            Some("100.67.0.167"),
            false, // Disable RAVENNA extensions
        );

        // RAVENNA-specific attributes should NOT be present
        assert!(!sdp.contains("a=clock-domain:"));
        assert!(!sdp.contains("a=framecount:"));
        assert!(!sdp.contains("a=sync-time:"));

        // But standard AES67 attributes should still be present
        assert!(sdp.contains("a=ts-refclk:ptp=IEEE1588-2008:ec-46-70-ff-fe-0a-a1-81:42"));
        assert!(sdp.contains("a=mediaclk:direct=0"));
    }

    #[test]
    fn test_convert_clock_id_to_sdp_format() {
        // Test conversion from colon-separated (PtpInfo format) to hyphen-separated lowercase (SDP format)
        // Lowercase is used for better interoperability with RAVENNA/AES67 devices
        assert_eq!(
            convert_clock_id_to_sdp_format("00:11:22:33:44:55:66:77"),
            "00-11-22-33-44-55-66-77"
        );

        // Test with actual EUI-64 format clock ID - should be lowercased
        assert_eq!(
            convert_clock_id_to_sdp_format("EC:46:70:FF:FE:02:E2:3A"),
            "ec-46-70-ff-fe-02-e2-3a"
        );

        // Test with all zeros (placeholder)
        assert_eq!(
            convert_clock_id_to_sdp_format("00:00:00:FF:FE:00:00:00"),
            "00-00-00-ff-fe-00-00-00"
        );
    }

    #[test]
    fn test_sanitize_session_name_normal() {
        assert_eq!(sanitize_session_name("My Stream"), "My Stream");
        assert_eq!(sanitize_session_name("AES67 Output 1"), "AES67 Output 1");
    }

    #[test]
    fn test_sanitize_session_name_removes_forbidden_chars() {
        // Remove NUL, CR, LF
        assert_eq!(sanitize_session_name("Test\0Name"), "TestName");
        assert_eq!(sanitize_session_name("Test\rName"), "TestName");
        assert_eq!(sanitize_session_name("Test\nName"), "TestName");
        assert_eq!(sanitize_session_name("Test\r\nName"), "TestName");
    }

    #[test]
    fn test_sanitize_session_name_empty_returns_space() {
        // RFC 4566: s= MUST NOT be empty
        assert_eq!(sanitize_session_name(""), " ");
        assert_eq!(sanitize_session_name("   "), " ");
        assert_eq!(sanitize_session_name("\n\r"), " ");
    }

    #[test]
    fn test_sanitize_session_name_preserves_unicode() {
        assert_eq!(sanitize_session_name("Ström Audio"), "Ström Audio");
        assert_eq!(sanitize_session_name("日本語"), "日本語");
    }
}
